<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="lidar_radius" value="0.05"/>
    <xacro:property name="lidar_length" value="0.03"/>

    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>

            <material name="black"/>

        </visual>
    </link>

    <gazebo reference="lidar_link">
        <material>Gazebo/Black</material>

        <sensor name='gpu_lidar' type='gpu_lidar'>"
            <gz_frame_id>robot/lidar_link</gz_frame_id>
            <pose>0 0 0 0 0 0</pose>
            <topic>/scan</topic>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>${-pi / 2}</min_angle>
                        <max_angle>${pi / 2}</max_angle>
                    </horizontal>

                    <vertical>
                        <samples>1</samples>
                        <resolution>0.01</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>0</max_angle>
                    </vertical>
                </scan>

                <range>
                    <min>0.08</min>
                    <max>12.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <always_on>true</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="${base_length / 2} 0 0" rpy="0 0 0"/>
    </joint>

</robot>