<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_width" value="0.1"/>
    <xacro:property name="camera_length" value="0.05"/>
    <xacro:property name="camera_height" value="0.03"/>

    <material name="aluminum">
      <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>

            <material name="aluminum"/>

        </visual>
    </link>
    
    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${base_length / 2 - camera_length} 0 ${base_height / 2 + camera_height / 2}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="camera_link">

        <sensor name='depth_camera' type='depth_camera'>"
            <gz_frame_id>robot/camera_link</gz_frame_id>
            <always_on>true</always_on>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.51843645</horizontal_fov>
                <image>
                    <width>848</width>
                    <height>480</height>
                    <format>R_FLOAT32</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>10</far>
                </clip>
                <lens>
                    <intrinsics>
                    <fx>421.61578369140625</fx>
                    <fy>421.61578369140625</fy>
                    <cx>422.2854309082031</cx>
                    <cy>236.57237243652344</cy>
                    <s>0</s>
                    </intrinsics>
                </lens>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
        </sensor>

        <sensor name="color_sensor_frame" type="camera">
            <gz_frame_id>robot/camera_link</gz_frame_id>
            <update_rate>30</update_rate>
            <always_on>true</always_on>
            <camera>
                <horizontal_fov>1.20427718</horizontal_fov>
                <image>
                    <width>848</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>50</far>
                </clip>
                <lens>
                    <intrinsics>
                    <fx>615.9603271484375</fx>
                    <fy>616.227294921875</fy>
                    <cx>419.83026123046875</cx>
                    <cy>245.1431427001953</cy>
                    <s>0</s>
                    </intrinsics>
                </lens>
            </camera>
        </sensor>
    </gazebo>
</robot>